version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: gotodo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432